Update finalizing-setup.txt
hacks-guide/Guide_3DS pull request #1850
Opened 2021-03-01 15:22 UTC by TheGoofBall64

it updates finalizing settup page to giving the user more things to try to get an update to work. To help Avoiding unnecessary CTR transferring

2021-03-01 16:06 UTC, win9x-se commented
a few things

Unplugging routers can cause a ton of problems, i.e. needing to reflash or otherwise fix it, not all routers are made to be unplugged on whim

Not everyone has access to their router/internet system and thus can't do things like disable router wide firewall, etc

The 3DS itself doesn't have a firewall, so that wouldn't apply

Most of these steps are redundant as a lot of the time, it comes down to "bring your console closer, and reboot".

2021-03-01 16:12 UTC, MechanicalDragon0687 commented
the more recent issues we have had with people updating is due to their wifi connection settings still being set for the dns hacks or being broken. I have had my connection fail even after clearing the dns settings and had to recreate it completely to fix it.

Perhaps adding a Wifi Troubleshooting section on the troubleshooting page would make more sense considering there are several methods that require wifi connection manipulation now?

2021-03-01 18:21 UTC, TheGoofBall64 commented
Yeah. Your probably right. I'll add something like that

2021-03-01 18:46 UTC, TheGoofBall64 commented
> Unplugging routers can cause a ton of problems, i.e. needing to reflash or otherwise fix it, not all routers are made to be unplugged on whim

Yeah your right. I'll fix that

> Not everyone has access to their router/internet system and thus can't do things like disable router wide firewall, etc

This is kind of a redundant argument. Yes it is almost never the problem, but If you are having problems and have access to, and the know how, to disable your firewall, go ahead and try. it shouldn't matter if some people can not access it. It's still a potential problem.

> The 3DS itself doesn't have a firewall, so that wouldn't apply

Yes, the 3ds doesn't have any sort of firewall. But your WiFi itself could have a firewall, and could block specific things your 3ds calls for. As per Nintendo points out in their own network troubleshooting guide

> Most of these steps are redundant as a lot of the time, it comes down to "bring your console closer, and reboot".

Yes. You are right. But again, I myself has had to restart my WiFi network multiple times. Even after going closer and rebooting. And even had to try another network entirely because my WiFi just didn't work that day. This is why (I'm going to) adding a troubleshooting section on there like Randal suggested would be a good idea. Most of the time it does come down to "bring your console closer, and reboot". But it still happens

2021-03-01 18:49 UTC, MechanicalDragon0687 commented
adding a "check the firewall settings in your router" is more likely to confuse the common user of the guide. If they have firewall settings in the router blocking things, and they set them up, it is likely unnecessary to tell them to check them. if they have firewall settings in the router and they didnt, telling them to check it is moot

2021-03-01 18:53 UTC, TheGoofBall64 commented
Ok. I went add ''check firewall" then

2021-03-01 19:01 UTC, TheGoofBall64 commented
If you have any other suggestions on what I should add to the troubleshooting section please go ahead. Thank you

2021-03-01 21:58 UTC, lilyuwuu requested changes

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. You get an error while trying to use WiFi (during system update, loading the browser/Eshop, ect.)
This is a statement. It shouldn't be a 'step' in the troubleshooting.

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. You get an error while trying to use WiFi (during system update, loading the browser/Eshop, ect.)
`Eshop` -> `eShop`; `ect.` -> `etc.`

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try setting your DNS settings to "auto"
"Auto" should be capitalized

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try deleting your WiFi connection/s, then sign into your Wifi again
Use consistent capitalization of WiFi

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try conecting to a different WiFi conection (mobile hotspot, ect.)
`ect.` -> `etc.`

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try moving closer to your WiFi router, and rebooting your 3DS
Remove the comma

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try again later (Nintendo servers are down, ect.)
This doesn't really work as an `etc.` If your only example is Nintendo servers being down, use `Nintendo servers may be down. Try again later` or something.

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. If this still gives you an error, [follow CTRTransfer](ctrtransfer), then try again
"this" is ambiguous in this context; needs to be reworded

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try deleting your WiFi connection/s, then sign into your Wifi again
`Sign in` implies that there's a portal/login page, which the 3DS doesn't support. Use `connect to` instead.

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. For support (in English), join [Nintendo Homebrew on Discord](https://discord.gg/MWxPgEp)
The order of this steps should be from easiest to hardest to do, which would be (IMO):

1. Set DNS to Auto
2. Move closer to router
3. Delete and re-add WiFi network
4. Try a different WiFi connection
5. Nintendo's servers might be down
6. CTRTransfer
7. Ask for help

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/finalizing-setup.txt
> +  + If this still gives you an error, [follow this troubleshooting guide](troubleshooting#wifi-connection-errors-after-installing-cfw), then try updating again
You are suggesting multiple ideas, each of which should be tried before updating again. This isn't necessarily clear from the text of your troubleshooting guide.

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try again later (Nintendo servers are down, ect.)
`ect.` -> `etc.`

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. For support (in English), join [Nintendo Homebrew on Discord](https://discord.gg/MWxPgEp)
I don't think `Try` should be at the beginning of every sentence (use the form used with CTRTransfer, which is `then try again`). It's left unspoken what to do after you reboot you WiFi router/set DNS to auto/whatever, which is unclear.

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +## WiFi connection errors after installing CFW
This is a bit vague. The only case we're really worried about is system updating, as Nintendo doesn't offer any error codes when something goes wrong during system updates. If an error occurs in the browser or in eShop, there is usually an error code that goes along with it. We're not dealing with browser or eShop connection issues in this portion of the guide, so I don't think it should be so vague.

This also means an online services ban could be misinterpreted as a WiFi connection error.

2021-03-01 21:58 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Try deleting your WiFi connection/s, then sign into your Wifi again
A user should only have one WiFi connection that they should be connecting to at this moment. I don't see the need to delete *multiple* connections.

2021-03-02 01:57 UTC, TheGoofBall64 reviewed
fixed.

but I never put in to try and hold `A+R+L+Up(DPad) on boot (to attempt an update in recovery mode)` anywhere. and I'm having trouble on how to implement it. because the ideal situation is to try this on every option after "move closer to your WiFi". do you have any ideas on how to implement this

2021-03-02 02:22 UTC, lilyuwuu requested changes

2021-03-02 02:22 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. If none of the options above worked, [follow CTRTransfer](ctrtransfer), then try updating again
The beginning of each point should be capitalized.

2021-03-02 02:22 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. conect to a different WiFi conection (mobile hotspot, etc.)
"Connect" is misspelled, as is "connection". 

"Connect to a different WiFi connection" is a bit repetitive, but the 3DS calls them 'connections' so it *should* be fine...

It's a bit awkward to use `etc.` when you only have one item as an example. If the only 'different WiFi connection' you can think of is a mobile hotspot, it might be better to just word it as "Connect to a different WiFi connection, like a mobile hotspot [or something else]"

2021-03-02 02:22 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +  + You get an error while trying to use WiFi (during system update)
An error when trying to use WiFi during system update, as opposed to trying to use something else?...

The best way to clarify this section would be to show that the error that people should see is "An error has occurred".

2021-03-02 02:22 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +  + reboot your 3DS after each option and try updating again
option -> step; if it's an option, then people can follow them out of order (though they likely wouldn't)

2021-03-02 02:22 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. delete your WiFi connection, then connect to your WiFi again
A bit awkwardly worded IMO. 'm partial to using the term `reconnect` but it might be unnecessarily vague.

2021-03-02 02:23 UTC, lilyuwuu commented
A Safe Mode step could just be
`1. Update from Safe Mode by turning off the console, holding L+R+Up+A on boot, and following the prompts` or something

2021-03-02 02:23 UTC, TheGoofBall64 commented on _pages/en_US/troubleshooting.txt
> +1. If none of the options above worked, [follow CTRTransfer](ctrtransfer), then try updating again
oh god. how did i miss that?

2021-03-02 06:42 UTC, lilyuwuu reviewed
The rest generally looks good to me!

2021-03-02 06:42 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +  + Reboot your 3DS after each step and try updating again
Maybe replace these two bullet points with a paragraph that reads

"Occasionally, updates may fail to install after installing CFW. To fix this, reboot your 3DS after each step of this section, then try updating again."

This would be in line with other troubleshooting steps that add more information. 

Alternatively, since this is currently only linked on Finalizing Setup, you could just have " Reboot your 3DS after each step, then try updating again" as one sentence.

Third idea: Don't have any text before the steps, then add "then try updating again" after each step.

2021-03-03 21:28 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +  + Occasionally, updates may fail to install after installing CFW. To fix this, reboot your 3DS after each step of this section, then try updating again.
This shouldn't be a bullet point/indented.

2021-03-03 21:28 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. If none of the steps above worked, [follow CTRTransfer](ctrtransfer), then try updating again
Is this intentional, as some way to discourage CTRTransfering? It's inconsistent to the rest of the text.

Also, "then try updating again" shouldn't be necessary because it's said at the beginning of this section.

2021-03-04 19:22 UTC, TheGoofBall64 commented on _pages/en_US/troubleshooting.txt
> +1. If none of the steps above worked, [follow CTRTransfer](ctrtransfer), then try updating again
no it wasn't intentional. sorry, ill fix that

2021-03-04 19:31 UTC, TheGoofBall64 commented on _pages/en_US/troubleshooting.txt
> +  + Occasionally, updates may fail to install after installing CFW. To fix this, reboot your 3DS after each step of this section, then try updating again.
fixed

2021-03-04 22:02 UTC, lilyuwuu approved these changes
Looks good

2021-03-09 01:29 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Update from Safe Mode by turning off the console, holding (A) + (Right Shoulder) + (Left Shoulder) + (D-Pad Up) on boot, and following the on screen prompts
A bit picky, but the guide uses the order of `(Left Shoulder) + (Right Shoulder) + (D-Pad Up) + (A)` to describe the buttons.

2021-03-09 01:29 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Update from Safe Mode by turning off the console, holding (A) + (Right Shoulder) + (Left Shoulder) + (D-Pad Up) on boot, and following the on screen prompts
There should be a hyphen between on and screen (on-screen).

2021-03-10 20:21 UTC, TheGoofBall64 commented
when will this get merged? It's been 6 days since any significant changes were made. and it was approved

2021-03-10 20:28 UTC, lilyuwuu commented
No one else has looked at it so I'm a bit hesitant to merge it. The policy is usually to get at least a couple people to look before merging. That's also why if you look at the PR history a lot of the changes that weren't to fix a typo or something smaller took a while to merge.

That being said, nothing will get done without a strict time limit so I'll go ahead and merge this in about 48 hours if no one else has any thoughts/opposition.

2021-03-10 20:40 UTC, win9x-se commented
troubleshooting seems to have an error with the numbering
![image](https://user-images.githubusercontent.com/51892981/110694620-d3a88600-81b6-11eb-9283-2cb424d4d5a0.png)

2021-03-10 20:41 UTC, MechanicalDragon0687 commented
> troubleshooting seems to have an error with the numbering
> ![image](https://user-images.githubusercontent.com/51892981/110694620-d3a88600-81b6-11eb-9283-2cb424d4d5a0.png)

this is normal. the numbering isnt hardcoded until built.

2021-03-10 20:42 UTC, win9x-se commented
> 
> 
> > troubleshooting seems to have an error with the numbering
> > ![image](https://user-images.githubusercontent.com/51892981/110694620-d3a88600-81b6-11eb-9283-2cb424d4d5a0.png)
> 
> this is normal. the numbering isnt hardcoded until built.

yeah i just realized that, sorry

2021-03-10 20:57 UTC, GlaZedBelmont commented on _pages/en_US/troubleshooting.txt
> + Occasionally, updates may fail to install after installing CFW. To fix this, reboot your 3DS after each step of this section, then try updating again.
We usually use "console" or "device" when talking about the 3DS, the rest of your edits don't say 3DS

2021-03-10 21:00 UTC, GlaZedBelmont commented on _pages/en_US/troubleshooting.txt
> +1. Nintendo servers may be down. Try again later
small nitpick but why do you say "[...] may be down. Try again later" then "[...], then try again" maybe using a comma on the former would be better

2021-03-10 21:05 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Update from Safe Mode by turning off the console, holding (Left Shoulder) + (Right Shoulder) + (D-Pad Up) + (A) on boot, and following the on-screen prompts
That is incorrect -- in English, verb tenses should be consistent. The first instance is "turning" (off the console), so the next ones should indeed be "holding" and "following". "Update" is separate.

2021-03-10 21:07 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +1. Nintendo servers may be down. Try again later
It'd technically be grammatically incorrect because "try again later" is a full sentence. You can use a semicolon to separate them though.

2021-03-11 05:18 UTC, TheGoofBall64 commented on _pages/en_US/troubleshooting.txt
> +1. Update from Safe Mode by turning off the console, holding (Left Shoulder) + (Right Shoulder) + (D-Pad Up) + (A) on boot, and following the on-screen prompts
I speak English as my main language. and even I never noticed this. I automatically write it with the correct verb tenses and everything

2021-03-14 22:21 UTC, merged