R4iSDHC GOLD Pro/R4iSDHC RTS LITE/R4iSDHC Dual-Core 2021 are no longer support ntrboot
hacks-guide/Guide_3DS pull request #1865
Opened 2021-03-28 10:35 UTC by OasisAkari

**Description**
I confirmed it from r4isdhc's official sale.
Since they replaced the mainboard used by the flashcard, the newer than 2020 model are no longer support ntrboot.

![image](https://user-images.githubusercontent.com/31803608/112749178-486f2300-8ff3-11eb-88ea-664e91c21e70.png)

Translation (Use google translate):
```
Sorry for bothering you.

At present, the new R4 cards cost by ￥cny 20 on the market starting in 2021 do not support magnet flashing at all.

The cards that can be supported are part of the cards before 2020 and some high-priced cards.

None of the cost by ￥cny 20 or so cards newly released in 2021 support magnet flashing.

Must find the old version. So as not to increase our interpretation work.

Thank you. .
```

2021-03-28 10:38 UTC, hansoljin commented
This needs to be looked further into. As far as I'm concerned, all carts from r4isdhc **.com** are supported. I haven't actually seen a 2021 **.com** cart yet (I doubt they're gonna release one at all), so it is yet to be seen.

However, it is definitely true that the r4isdhc **.com.cn** carts and the **.hk** carts don't support ntrboot (and never will.) 

Do you have an r4isdhc **.com** cart labeled 2021? If so, can you post a kernel? I could look into it a bit.

2021-03-28 11:07 UTC, OasisAkari commented
> r4isdhc **.com** cart labeled 2021

ahh I can confirm r4isdhc **.com** cart labeled 2021(Available for official sales in mainland China (http://cn.r4isdhc.com/distributor/)) uses mainboard are replaced to r4isdhc.com.cn‘s one. So the kernel are same to r4isdhc.com.cn

![image](https://user-images.githubusercontent.com/31803608/112749851-95ed8f00-8ff7-11eb-978e-57b654009e30.png)
![20210328185905](https://user-images.githubusercontent.com/31803608/112749881-cc2b0e80-8ff7-11eb-834f-249ef3416f7d.jpg)

2021-03-28 11:12 UTC, hansoljin commented
Oh, I see. Then yes, it won't support ntrboot.

2021-03-28 13:27 UTC, R-YaTian commented
> > r4isdhc **.com** cart labeled 2021
> 
> ahh I can confirm r4isdhc **.com** cart labeled 2021([Available for official sales in mainland China](http://cn.r4isdhc.com/distributor/)) uses mainboard are replaced to r4isdhc.com.cn's one. So the kernel are same to r4isdhc.com.cn
> 
> ![image](https://user-images.githubusercontent.com/31803608/112749851-95ed8f00-8ff7-11eb-978e-57b654009e30.png)
> ![20210328185905](https://user-images.githubusercontent.com/31803608/112749881-cc2b0e80-8ff7-11eb-834f-249ef3416f7d.jpg)

The card www.r4isdhc.com belong to www.r4i-sdhc.com, this card on your photo is a fake card which used r4isdhc.com.cn's mainboard.
No need to add this commit.
And this fake card also support ntrboot, just choose 'R4iSDHC Dual-Core (r4isdhc.com.cn) family'.

2021-03-28 14:26 UTC, OasisAkari commented
well, but I think this pr should leave in here for waiting for more people to check if so

2021-03-28 21:33 UTC, hansoljin commented
> > r4isdhc **.com** cart labeled 2021
> 
> ahh I can confirm r4isdhc **.com** cart labeled 2021([Available for official sales in mainland China](http://cn.r4isdhc.com/distributor/)) uses mainboard are replaced to r4isdhc.com.cn's one. So the kernel are same to r4isdhc.com.cn
> 
> ![image](https://user-images.githubusercontent.com/31803608/112749851-95ed8f00-8ff7-11eb-978e-57b654009e30.png)
> ![20210328185905](https://user-images.githubusercontent.com/31803608/112749881-cc2b0e80-8ff7-11eb-834f-249ef3416f7d.jpg)

I would wait until someone who has another r4isdhc **.com** cart to double check.

Also, we still don't have the proper flash backups for most of these, so I'd double check before saying all r4isdhc **.com.cn** ones will work with ntrboot.

2021-04-01 10:20 UTC, OasisAkari commented
> The card [www.r4isdhc.com](http://www.r4isdhc.com) belongs to [www.r4i-sdhc.com](http://www.r4i-sdhc.com), this card on your photo is a fake card which used r4isdhc.com.cn's mainboard.
> No need to add this commit.
> And this fake card also support ntrboot, just choose 'R4iSDHC Dual-Core (r4isdhc.com.cn) family'.

I just tested it, nope choose that model option will also pop up an unsupported prompt

2021-04-17 08:13 UTC, lilyuwuu commented on _pages/en_US/ntrboot.txt
> +| [**R4iSDHC RTS LITE 20XX**](http://www.nds-card.com/ProShow.asp?ProID=450) | $13.99 | 4.0b: September 3, 2024 | <= 11.14.0 | <= 1.4.5 | All R4iSDHC 20XX flashcarts are identical. 2013, 2021 and lat
Use "Only cartridges marked with a year between 2014 and 2020 are compatible." Not sure how to make that concise and to clarify that it's inclusive of both 2014 and 2020, though...

2021-05-06 08:32 UTC, hansoljin requested changes

2021-05-06 08:32 UTC, hansoljin commented on _pages/en_US/ntrboot.txt
> +| [**R4iSDHC RTS LITE 20XX**](http://www.nds-card.com/ProShow.asp?ProID=450) | $13.99 | 4.0b: September 3, 2024 | <= 11.14.0 | <= 1.4.5 | Only r4isdhc **.com** carts are supported. All R4iSDHC 20XX f
If we wanted it simple, why not replace it all with something like:

`Only r4isdhc **.com** carts marked with a year between 2014 and 2020 are compatible.`

The R4iSDHC 20XX identical thing isn't really important if we make it clear specifically which ones work, anyway.

2021-05-06 08:32 UTC, hansoljin commented on _pages/en_US/ntrboot.txt
> +| **R4iSDHC Dual-Core 20XX** | | 4.0b: September 3, 2024 | <= 11.14.0 | <= 1.4.5 | Only r4isdhc **.com** carts are supported. All R4iSDHC 20XX flashcarts are identical. Only cartridges marked with a
same as above.

2021-05-09 18:35 UTC, OasisAkari commented
xd i'm stupid

2021-05-26 02:01 UTC, merged

2021-11-15 00:28 UTC, Rot-gut commented
Does anyone have a backup .bin of the R4 Gold Pro 2021 card? I accidentally flashed R4 SDHC ntrboot onto it using a DSi and now it's a brick.