Grammar fixes
hacks-guide/Guide_3DS pull request #1966
Opened 2022-01-30 18:40 UTC by zsotroav

**Description**

All changes made were based on Grammarly's suggestions. I didn't make big changes, only small grammar improvements (typos, missing commas, etc.)

2022-01-30 19:05 UTC, aspargas2 requested changes
There's a few changes here which definitely are wrong.

2022-01-30 19:05 UTC, aspargas2 commented on _pages/en_US/move-emunand.txt
> +To identify a `<TitleID>.gbavc.sav` file's Title ID, you can get a listing of all games on the system and their corresponding Title IDs by hovering over `[A:] SYSNAND SD`, holding (R), and pressing (
This is uh, wrong. It was fine like it was.

2022-01-30 23:52 UTC, lifehackerhansol requested changes

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/ctrtransfer.txt
> +1. Once the transfer has been completed, press (A) to continue
```suggestion
1. Once the transfer is complete, press (A) to continue
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(fredtool).txt
> +1. When the process has been completed, download your modified DSiWare archive from the site
```suggestion
1. When the process is complete, download your modified DSiWare archive from the site
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(kartdlphax).txt
> +1. Once it has been completed, press (A) to reboot your device
```suggestion
1. Once it is complete, press (A) to reboot your device
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(ntrboot).txt
> +1. Once it has been completed, force your device to power off by holding down the power button
```suggestion
1. Once it is complete, force your device to power off by holding down the power button
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(pichaxx).txt
> +1. Once it has been completed, press (A) to reboot your device
```suggestion
1. Once it is complete, press (A) to reboot your device
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(safeb9sinstaller).txt
> +1. Once it has been completed, press (A) to reboot your device
```suggestion
1. Once it is complete, press (A) to reboot your device
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(soundhax).txt
> +1. Once it has been completed, press (A) to reboot your device
```suggestion
1. Once it is complete, press (A) to reboot your device
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/move-emunand.txt
> +1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has been completed
```suggestion
1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it is complete
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/move-emunand.txt
> +1. Once it has been completed, press (A) to continue
```suggestion
1. Once it is complete, press (A) to continue
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/region-changing.txt
> +1. Once the transfer has been completed, press (A) to continue
```suggestion
1. Once the transfer is complete, press (A) to continue
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/region-changing.txt
> +1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has been completed
```suggestion
1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it is complete
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/seedminer.txt
> +1. When the process has been completed, download your `movable.sed` file from the site
```suggestion
1. When the process is complete, download your `movable.sed` file from the site
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/uninstall-cfw.txt
> +1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has been completed
```suggestion
1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it is complete
```

2022-01-30 23:52 UTC, lifehackerhansol commented on _pages/en_US/updating-b9s.txt
> +1. Once it has been completed, force your device to power off by holding down the power button
```suggestion
1. Once it is complete, force your device to power off by holding down the power button
```

2022-01-31 10:55 UTC, lilyuwuu reviewed
Everything else looks good at a glance

2022-01-31 10:55 UTC, lilyuwuu commented on _pages/en_US/troubleshooting.txt
> +### SigHaxed FIRM was not installed! Check the lower screen for more info.
This should not be changed as it is based on the message that shows up on the 3DS itself

2022-01-31 15:30 UTC, lifehackerhansol requested changes

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/uninstall-cfw.txt
> +1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has been completed
This was also not added lol

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/seedminer.txt
> +1. When the process has been completed, download your `movable.sed` file from the site
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/region-changing.txt
> +1. Once the transfer has been completed, press (A) to continue
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/region-changing.txt
> +1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has been completed
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/move-emunand.txt
> +1. If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has been completed
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/move-emunand.txt
> +1. Once it has been completed, press (A) to continue
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(ntrboot).txt
> +1. Once it has been completed, force your device to power off by holding down the power button
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(fredtool).txt
> +1. When the process has been completed, download your modified DSiWare archive from the site
This was not added.

2022-01-31 15:30 UTC, lifehackerhansol commented on _pages/en_US/ctrtransfer.txt
> +1. Once the transfer has been completed, press (A) to continue
This was not added.

2022-01-31 20:37 UTC, lifehackerhansol approved these changes

2022-02-11 05:50 UTC, merged