add alternate exploits (finish 11.17 guide support)
hacks-guide/Guide_3DS pull request #2269
Opened 2023-05-24 08:28 UTC by lilyuwuu

a.k.a. "the worst structural change in the history of this guide"

War. War never changes. In the year 2019, my great-great grandfather, serving in the army, wondered when he'd get to install CFW on his 3DS for free. He got his wish when zoogie released [Seedminer](https://github.com/zoogie/seedminer) and [BannerBomb3](https://github.com/zoogie/Bannerbomb3), granting free CFW to the vast majority of retail 3DSes in the world.

The Modders awaited Banmageddon; instead, something miraculous happened. We began to use BannerBomb3 not as a weapon, but as a nearly limitless source of power.

People enjoyed luxuries once thought the realm of science fiction. [Additional free CFW methods](https://github.com/zoogie/unSAFE_MODE/), [the return of an exploit long thought dead](https://github.com/zoogie/new-browserhax), practically [one-click install custom firmware](https://github.com/TuxSH/universal-otherapp). But then, on [March 27th, 2023](https://en-americas-support.nintendo.com/app/answers/detail/a_id/57847/~/wii-u-%26-nintendo-3ds-eshop-discontinuation-q%26a), people awoke from the Nintendo dream.

Years of consumption lead to [shortages of every major exploit](https://twitter.com/mattgcn/status/1660819460859764737). The entire guide unraveled. Simplicity became a distant memory. It is still the year 2023. We stand on the brink of [total war](https://wiki.hacks.guide/wiki/3DS:Alternate_Exploits), and I am afraid. For myself, for this guide, for all the people who want to install CFW - because if my time in the army taught me one thing:

It's that war? War never changes.

---

This PR ties up loose ends caused by 11.17 and brings the guide back to as normal of a state as it can be with BB3 being patched. The following pages are created:

- Seedminer (Mii) for Mii mining, which is the only free way to install CFW on O3DS 11.15
- Alternate Exploits, which are the only way to install CFW on O3DS 11.17
- Seedminer (Alternate), for use with Dumping eShop DSiWare and movable-requiring HBL entrypoints
- Dumping eShop DSiWare, part of the Seedminer + DSiWare + Fredtool sequence
- Several Homebrew Launcher pages, part of the [HBL] + [HBL-USM / nimhax+Frogtool) sequence
  - Homebrew Launcher (freakyhax)
  - Homebrew Launcher (ninjhax2-dx)
  - Homebrew Launcher (PicHaxx)
  - Homebrew Launcher (smilehax-IIe)
  - Homebrew Launcher (steelhax)
 
As well as a few logical changes to account for 11.17 and these new pages:

- Dumping movable (nimhax) tells people to skip the page if they already have movable.sed
- BannerBomb3 is completely removed from the nimhax page
- All Homebrew Launcher methods use one include
   - HBL (super-skaterhax) is modified to use this include
- Updating Firmware (KOR-TWN) split into KOR and TWN pages, since KOR goes to Seedminer as normal and TWN goes to Seedminer (TWN) -> BannerBomb3-Fredtool (TWN)
- Fredtool adds link to 11.15.0 with ample brick warning (**this may be a very bad idea, may just split this page for safety reasons**)
  - Since the page is not currently split, the normal Installing boot9strap (Fredtool) tries to be as DSiBin-agnostic as possible

At time of writing, **this PR does not make the JS changes required for these pages to be easliy accessible**. Table of Contents / progress bar needs to be updated accordingly, as does the version selector and Site Navigation pages.

This also works under the assumption that USA otherapps are fixed, which is not currently (totally) the case.

2023-05-24 08:42 UTC, Gruetzig reviewed
sussy

2023-05-24 08:42 UTC, Gruetzig commented on _pages/en_US/homebrew-launcher-(steelhax).txt
> +1. Open [https://3dstools.nhnarwhal.com/#/steelhax the SteelHax Save Tool website] on your computer
dont think thats how links work

2023-05-24 08:44 UTC, Gruetzig commented on _pages/en_US/seedminer-(mii).txt
> +1. Open the [https://zoogie.github.io/web/miiqr/ editMii] website on your computer
forgot one

2023-05-24 19:10 UTC, lilyuwuu commented on _pages/en_US/dumping-eshop-dsiware.txt
> +    + If you have multiple <ID1> folders, follow the instructions [here(https://3ds.hacks.guide/troubleshooting#bannerbomb3)
to get to this page, people would have done seedminer, which should have resolved the id0 thing

2023-05-24 19:10 UTC, lilyuwuu commented on _pages/en_US/homebrew-launcher-(pichaxx).txt
> +1. Open [https://3dstools.nhnarwhal.com/#/pichaxx the PicHaxx Injector website] on your computer
wikitext, my arch-nemesis

2023-05-24 20:58 UTC, lifehackerhansol requested changes

2023-05-24 20:58 UTC, lifehackerhansol commented on _pages/en_US/alternate-exploits.txt
> +If none of the above options are available to you, this is the cheapest available option. A preflashed ntrboot-compatible cartridge can be purchased [here](https://www.aliexpress.com/item/10050053376
I thought we were against putting volatile links in the guide

2023-05-24 20:58 UTC, lifehackerhansol commented on _pages/en_US/include/hbl-common-exploits-movable.txt
> +1. Power off your device
can we just use the `safemodecheck` include for this one in each page instead of doing it again here

like 
```
#### Section II - Hardware Button Check
// include safemodecheck

---
// include hbl-common-exploits
```

2023-05-24 20:58 UTC, lifehackerhansol commented on _pages/en_US/updating-firmware-(kor).md
> +### TWN 3DS users (e.g. 11.16.0-15T)
This PR seems to split KOR and TWN update pages, yet this was left behind

2023-05-24 21:01 UTC, lilyuwuu commented on _pages/en_US/include/hbl-common-exploits-movable.txt
> +1. Power off your device
yeah sure i guess

2023-05-24 21:02 UTC, lilyuwuu commented on _pages/en_US/alternate-exploits.txt
> +If none of the above options are available to you, this is the cheapest available option. A preflashed ntrboot-compatible cartridge can be purchased [here](https://www.aliexpress.com/item/10050053376
i dunno, i think it makes sense to link people the actual cart that they need.

Maybe we could have this link be a redirect that we can easily change the destination of? That way the actual link doesn't cause a translation update every time it needs to be changed.

2023-05-24 21:08 UTC, lifehackerhansol requested changes

2023-05-24 21:08 UTC, lifehackerhansol commented on _pages/en_US/homebrew-launcher-(smilehax-iie).txt
> +This method of using Seedminer for further exploitation uses your `movable.sed` file to write a custom save file for SmileBASIC, which can then be used to launch the Homebrew Launcher.
This exploit doesn't use seedminer

2023-05-24 21:08 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(fredtool-11.15).txt
> +Once we have a DSiWare backup, inject it into the DS Internet Settings application.
This sentence shouldn't be imperative

2023-05-24 21:08 UTC, lifehackerhansol commented on _pages/en_US/seedminer-(mii).txt
> +If you are on Linux, replace `py -3` with `python3` in all commands.
This also applies to macOS. Not that I think macOS users will be able to follow this in a reasonable amount of time, but just for the sake of clarity.

macOS also comes with python3 preinstalled iirc.

2023-05-24 21:08 UTC, lifehackerhansol commented on _pages/en_US/updating-firmware-(twn).txt
> +title: "Updating Firmware (KOR)"
This file is named TWN, but says KOR here

2023-05-24 21:12 UTC, lilyuwuu commented on _pages/en_US/homebrew-launcher-(smilehax-iie).txt
> +This method of using Seedminer for further exploitation uses your `movable.sed` file to write a custom save file for SmileBASIC, which can then be used to launch the Homebrew Launcher.
me when i go robot mode

2023-05-24 21:13 UTC, lilyuwuu commented on _pages/en_US/installing-boot9strap-(fredtool-11.15).txt
> +Once we have a DSiWare backup, inject it into the DS Internet Settings application.
une fois que nous nous avons le backup du dsiware injectez-le à l'appli ds internet settings

2023-05-24 21:17 UTC, lilyuwuu commented on _pages/en_US/alternate-exploits.txt
> +If none of the above options are available to you, this is the cheapest available option. A preflashed ntrboot-compatible cartridge can be purchased [here](https://www.aliexpress.com/item/10050053376
i also just realized that the message for this sentence is incomplete lol oops

2023-05-24 21:17 UTC, lifehackerhansol commented on _pages/en_US/installing-boot9strap-(fredtool-11.15).txt
> +Once we have a DSiWare backup, inject it into the DS Internet Settings application.
je ne sais pas ce que tu as dit

2023-05-24 21:20 UTC, lifehackerhansol commented on _pages/en_US/alternate-exploits.txt
> +If none of the above options are available to you, this is the cheapest available option. A preflashed ntrboot-compatible cartridge can be purchased [here](https://www.aliexpress.com/item/10050053376
Despite the constant negative press covfefe

2023-05-24 21:23 UTC, lifehackerhansol commented
ok so the get-started directory is as such?

```
1.0-11.3: soundhax
11.4-11.13, no cart update: ssloth
11.4-11.14, O3DS: safecerthax
11.15 N3DS: update and do super-skaterhax
11.15 KOR/TWN: update and do seedminer
11.15 O3DS: Mii mine
11.16: Seedminer
11.16 KOR, 11.17: super-skaterhax
```

2023-05-24 21:23 UTC, lifehackerhansol commented
or we can specifically just do seedminer on 11.16 KOR, I guess it really does not matter

2023-05-24 21:24 UTC, lilyuwuu commented
might be easier if we flowchart it

2023-05-24 21:26 UTC, lilyuwuu commented
never mind my mind is too broken to do it.
That sounds about right, just 11.17 o3ds -> alternate exploits, too

2023-05-24 22:02 UTC, lilyuwuu commented
![image](https://github.com/hacks-guide/Guide_3DS/assets/27717444/c838576f-7675-4fc9-b0e2-e3cf9cef9cbc)

2023-05-25 03:07 UTC, lifehackerhansol commented
I fixed this PR; it was a mess due to #2270 being merged, but it works now

2023-05-30 15:56 UTC, lifehackerhansol commented
Otherapps are fixed; anything more we need to do here?

2023-05-30 16:51 UTC, lifehackerhansol commented
PR ready for review / testing

2023-06-01 11:01 UTC, lilyuwuu commented on _pages/en_US/homebrew-launcher-(pichaxx).txt
> +In this section, you will create a hacked Pokémon Picross save file that, when used, will load the Homebrew Launcher on your device.
used -> loaded?

2023-06-01 11:03 UTC, lilyuwuu commented on _pages/en_US/seedminer-(alternate).txt
> +Select the method based on the application that you have installed on your 3DS.
May want to add a note here that no method here is necessarily "better" than the other and will have the same result in the end (granted, DSiWare is probably ultimately easier than pichaxx/steelhax)

2023-06-01 11:03 UTC, lilyuwuu commented on assets/js/_main.js
> +      "35": ["alternate-exploits", "seedminer-(alternate)", "dumping-eshop-dsiware", "installing-boot9strap-(fredtool-inject)", "finalizing-setup"],
thanks i hate it

2023-06-01 11:42 UTC, danny8376 commented on _pages/en_US/alternate-exploits.txt
> +This method uses a cartridge of the game Freakyforms Deluxe.
https://en.wikipedia.org/wiki/Freakyforms:_Your_Creations,_Alive!
seems to be
https://plutooo.github.io/freakyhax/
also mentioned on the original site, so i think it really do

2023-06-02 02:01 UTC, lifehackerhansol commented on _pages/en_US/alternate-exploits.txt
> +This method uses a cartridge of the game Freakyforms Deluxe.
It exists, but has long since been removed from eShop.

You could redownload it, but I'm not certain whether ninty decided to make this exploit harder to access digitally

2023-06-02 02:02 UTC, lifehackerhansol commented on assets/js/_main.js
> +      "35": ["alternate-exploits", "seedminer-(alternate)", "dumping-eshop-dsiware", "installing-boot9strap-(fredtool-inject)", "finalizing-setup"],
method number 35, what a time to be alive :roosip:

2023-06-02 02:04 UTC, lifehackerhansol commented on _pages/en_US/homebrew-launcher-(pichaxx).txt
> +In this section, you will create a hacked Pokémon Picross save file that, when used, will load the Homebrew Launcher on your device.
"[a] save file that, when loaded, will load"

idk if I like this change

2023-06-02 02:07 UTC, lifehackerhansol commented on _pages/en_US/homebrew-launcher-(ninjhax2-dx).txt
> +[Ninjhax2](https://github.com/smealum/ninjhax2.x) is an exploit for the game "Cubic Ninja" made by [smealum](https://github.com/smealum), compatible with system versions 9.0.0 through 11.17.0 for USA
we could remove supported versions from the first sentence entirely

2023-06-02 02:10 UTC, lifehackerhansol commented on _pages/en_US/alternate-exploits.txt
> +Alternatively, SmileBASIC (a paid game) can be used to get Homebrew Launcher without using Seedminer.
How do you propose we write that? I can't think of a good way to word it

2023-06-02 02:11 UTC, lilyuwuu commented on _pages/en_US/homebrew-launcher-(pichaxx).txt
> +In this section, you will create a hacked Pokémon Picross save file that, when used, will load the Homebrew Launcher on your device.
Ok yeah nvm LOL
loaded, will run?

2023-06-05 14:23 UTC, lilyuwuu commented on _pages/en_US/alternate-exploits.txt
> +Alternatively, SmileBASIC (a paid game) can be used to get Homebrew Launcher without using Seedminer.
can be resolved later

2023-06-05 14:23 UTC, lilyuwuu commented on _pages/en_US/homebrew-launcher-(ninjhax2-dx).txt
> +[Ninjhax2](https://github.com/smealum/ninjhax2.x) is an exploit for the game "Cubic Ninja" made by [smealum](https://github.com/smealum), compatible with system versions 9.0.0 through 11.17.0 for USA
done

2023-06-05 14:32 UTC, lilyuwuu commented
Most reviewed changes have been made. Others should be made outside of this PR.

11.17 update notice include (as well as the copy in get-started) have also been updated accordingly to remove the link to NH (since information is no longer rapidly evolving) and to remove the link to troubleshooter (since the guide now contains all of this information).

Otherwise, likely ready to merge. May want to pass this through one more round of review just in case. Or we can YOLO it.

2023-06-05 20:01 UTC, merged

2023-06-05 20:05 UTC, Gruetzig commented on _pages/en_US/homebrew-launcher-(ninjhax2-dx).txt
> +1. On your PC, open the browser and go to [ninjhax2-dx website](https://zoogie.github.io/web/nh2dx/)
super minor thing but add a the, "go to the ninjhax2-dx website" sounds more natural to me imo

2023-06-05 20:06 UTC, Gruetzig commented
oh im too late fuck