add kartminer7
hacks-guide/Guide_3DS pull request #2305
Opened 2023-07-04 00:25 UTC by lilyuwuu

**3ds.guide**: Well, zoogie, I made it, despite your directions.
**zoogie**: Ah, 3ds.guide, welcome. I hope you're prepared for an unforgettable exploit!
**3ds.guide**: Yeah.
*[zoogie runs to the kitchen, only to find Nintendo has patched BannerBomb3 and gasps in horror]*
**zoogie**: Oh, egads! My exploit is ruined! But what if I were to [get `movable.sed`](https://3ds.hacks.guide/seedminer) and [disguise it as my own extdata](https://github.com/zoogie/kartminer7)? *[chuckles]* Delightfully devilish, zoogie.

---

Adds the newly released and untested (well, I just tested it) Kartminer7 exploit, which uses Mario Kart 7 (the [best-selling Nintendo 3DS video game of all time](https://en.wikipedia.org/wiki/List_of_best-selling_Nintendo_3DS_video_games)) and the already existing Seedminer to install hax either via USM (working shoulders) or menuhax67 (broken shoulders).

In particular, this PR:

- Switches Installing boot9strap (kartdlphax) to "3DS ROP xPloit Injector (kartdlphax)"
    - An automatic redirect is added
- Branches kartdlphax into "Installing boot9strap (3DS ROP xPloit Injector-USM)" and "menuhax67 + nimhax (3DS ROP xPloit Injector)"
- Adds "3DS ROP xPloit Injector (Kartminer7), which is linked from Seedminer (Alternate)
- Adjusts language accordingly on related pages (alternate-exploits, site-navigation)

TODO:
- fix table of contents
- tell people how to restore their MK7 data

2023-07-04 04:06 UTC, lifehackerhansol requested changes

2023-07-04 04:06 UTC, lifehackerhansol commented on _pages/en_US/alternate-exploits.txt
> +Continue to [Seedminer (Alternate)](seedminer-(alternate))
Seedminer alternate is linked twice, first here and then right below this heading

If the intent is to use explicitly kartminer7 here, both headings should be merged

2023-07-04 04:06 UTC, lifehackerhansol commented on _pages/en_US/dumping-movable-(nimhax).txt
> -While this method is faster, it requires downloading a file with a torrent client. Do not follow this method if you're unable to use a torrent client.
Remove backslash, not needed after the below line is removed

2023-07-04 11:16 UTC, TheMasterOfMike commented on _pages/en_US/3dsropxploitinjector-(kartminer7).txt
> +If your shoulder buttons (L and R) are NOT working, continue to [menuhax67 + nimhax (3DS ROP xPloit Injector)](menuhax67-nimhax-(3dsropxploitinjector))
Is there any reason you would need _nimhax_ after kartminer7 - obviously you'd need menuhax67 (for a HBL entrypoint) but we already end up with a movable.sed as a result of needing seedminer to do kartminer7 so this just seems redundant.

(yes I'm aware this page is also linked for kartdlphax, and yes, kartdlphax would need nimhax in this case scenario)

2023-07-04 11:45 UTC, lifehackerhansol commented on _pages/en_US/3dsropxploitinjector-(kartminer7).txt
> +If your shoulder buttons (L and R) are NOT working, continue to [menuhax67 + nimhax (3DS ROP xPloit Injector)](menuhax67-nimhax-(3dsropxploitinjector))
You're right, this probably is redundant.

2023-07-04 16:44 UTC, lilyuwuu commented on _pages/en_US/3dsropxploitinjector-(kartminer7).txt
> +If your shoulder buttons (L and R) are NOT working, continue to [menuhax67 + nimhax (3DS ROP xPloit Injector)](menuhax67-nimhax-(3dsropxploitinjector))
Among Us is a 2018 [online multiplayer](https://en.wikipedia.org/wiki/Online_multiplayer) [social deduction game](https://en.wikipedia.org/wiki/Social_deduction_game) developed and published by American game studio Innersloth. The game was inspired by the party game [Mafia](https://en.wikipedia.org/wiki/Mafia_(party_game)) and the [science fiction](https://en.wikipedia.org/wiki/Science_fiction_film) [horror](https://en.wikipedia.org/wiki/Horror_film) film [The Thing](https://en.wikipedia.org/wiki/The_Thing_(1982_film)). The game allows for [cross-platform play](https://en.wikipedia.org/wiki/Cross-platform_play), released on [iOS](https://en.wikipedia.org/wiki/IOS) and [Android](https://en.wikipedia.org/wiki/Android_(operating_system)) devices in June 2018 and on [Windows](https://en.wikipedia.org/wiki/Windows) later that year in November. The game was ported to the [Nintendo Switch](https://en.wikipedia.org/wiki/Nintendo_Switch) in December 2020 and on the [PlayStation 4](https://en.wikipedia.org/wiki/PlayStation_4), [PlayStation 5](https://en.wikipedia.org/wiki/PlayStation_5), [Xbox One](https://en.wikipedia.org/wiki/Xbox_One) and [Xbox Series X/S](https://en.wikipedia.org/wiki/Xbox_Series_X/S) in December 2021. A virtual reality adaptation, [Among Us VR](https://en.wikipedia.org/wiki/Among_Us_VR), was released on November 10, 2022.

2023-07-04 18:40 UTC, TheMasterOfMike commented
75d7ba4 does solve the kartminer7 case, but kartdlphax still needs to do nimhax, thus breaking the menuhax67 -> FrogTool path for kartdlphax

2023-07-04 18:45 UTC, lilyuwuu commented
so true i hate this

2023-07-04 18:51 UTC, TheMasterOfMike commented
> so true i hate this

I mean the most basic solution would probably be to just make separate pages (e.g. menuhax67 + nimhax for kartdlphax and menuhax67 + FrogTool for kartminer7) but that probably isn't the most ideal thing in the world.

2023-07-04 19:17 UTC, lilyuwuu commented
the wiki resolves this by having one page for telling people to hit y to install menuhax but that isn't ideal since it also doesn't tell people how to run it. This is probably the way to go

2023-07-04 20:56 UTC, TheMasterOfMike commented on _pages/en_US/installing-boot9strap-(3dsropxploitinjector-usm).txt
> +You will **not** need to use your **source 3DS** to complete any further steps on this guide. Any further steps should only be completed on the **target 3DS**.
As this page is also linked to from kartminer7, this line could potentially be really confusing (as this is not applicable to kartminer7)

2023-07-04 20:57 UTC, TheMasterOfMike commented on _pages/en_US/menuhax67-frogtool-(3dsropxploitinjector).txt
> +You will **not** need to use your **source 3DS** to complete any further steps on this guide. Any further steps should only be completed on the **target 3DS**.
This line doesn't make sense since the only way you get here is through kartminer7 (since kartdlphax needs nimhax and goes through its own page) and kartminer7 only needs one 3DS

2023-07-04 20:58 UTC, TheMasterOfMike commented on _pages/en_US/menuhax67-frogtool-(3dsropxploitinjector).txt
> +* The latest release of [nimhax](https://github.com/luigoalma/nimhax/releases/latest) (the nimhax `.zip` file)@
this doesn't make sense to link in this path due to reasons described earlier and also that this doesn't end up being used by anything on this page.

2023-07-13 02:20 UTC, lifehackerhansol requested changes

2023-07-13 02:20 UTC, lifehackerhansol commented on _pages/en_US/alternate-exploits.txt
this page links to installing-boot9strap-(kartdlphax); should be fixed to 3dsropxploitinjector-(kartdlphax)

2023-07-13 02:20 UTC, lifehackerhansol commented on _pages/en_US/3dsropxploitinjector-(kartminer7).txt
> +  - installing-boot9strap-(kartdlphax)
this page should not redirect from kartdlphax

2023-07-13 02:20 UTC, lifehackerhansol commented on _pages/en_US/3dsropxploitinjector-(kartdlphax).txt
> +If your shoulder buttons (L and R) are working, continue to [Installing boot9strap (3DS ROP xPloit Injector-USM)]
URL path not specified

2023-07-13 02:20 UTC, lifehackerhansol commented on _pages/en_US/menuhax67-nimhax-(3dsropxploitinjector).txt
> +Once you have your console's encryption key (`movable.sed`), you can use it in conjunction with Frogtool, which uses your `movable.sed` file to inject and take advantage of JPN Flipnote Studio. \
Remove trailing backslash

2023-07-13 02:20 UTC, lifehackerhansol commented on _pages/en_US/3dsropxploitinjector-(kartminer7).txt
> +1. If the exploit was successful, the **target 3DS** will have booted into the 3DS ROP xPloit Injector
what target 3DS?

2023-07-13 02:20 UTC, lifehackerhansol commented on _pages/en_US/3dsropxploitinjector-(kartminer7).txt
> +If your shoulder buttons (L and R) are working, continue to [Installing boot9strap (3DS ROP xPloit Injector-USM)]
ditto

2023-07-18 19:34 UTC, danny8376 commented
just notice one thing, it seems that it lacks Launcher.dat for menuhax?

2023-07-18 21:20 UTC, TheMasterOfMike commented
Additionally, with https://github.com/hacks-guide/Guide_3DS/commit/3f20c71dfccfa38015080deae46179dd9eb38928, it should now just be possible to have both kartdlphax and kartminer7 go menuhax67 -> FrogTool should the user not have functional shoulder buttons

2023-07-18 23:35 UTC, lilyuwuu commented
reworking due to #2319

2023-07-18 23:35 UTC, closed without merging